# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fastapi_api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "23000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: